### ISSUE TITLE
No available formula with the name "sdl"

### ISSUE THREAD

**Issue by kersti-h** [skyzyx/homebrew-ffmpeg#6]
Hello,

Installing `ffmpeg-skyzyx` doesn't seem to work on new Homebrew installations:

```
% brew install ffmpeg-skyzyx
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
Warning: No available formula with the name "sdl" (dependency of skyzyx/ffmpeg/ffmpeg-skyzyx). Did you mean sdl2, msdl, sd, sdf, sdb or gdl?
==> Searching for similarly named formulae and casks...
==> Formulae
cdogs-sdl       sdl2 ✔          sdl2_sound      sdl_net         sd
gowsdl          sdl2_gfx        sdl2_ttf        sdl_rtf         sdf
msdl            sdl2_image      sdl_gfx         sdl_sound       sdb
neopop-sdl      sdl2_mixer      sdl_image       sdl_ttf         gdl
sdl12-compat ✔  sdl2_net        sdl_mixer       sdlpop

To install cdogs-sdl, run:
  brew install cdogs-sdl

==> Casks
sdm                                      sol

To install sdm, run:
  brew install --cask sdm
```

The origin of the problem is that `ffmpeg-skyzyx` declares the following dependencies ([see source](https://github.com/skyzyx/homebrew-ffmpeg/blob/master/Formula/ffmpeg-skyzyx.rb)):

```
  depends_on "sdl"
  depends_on "sdl2"
```

However, `sdl` no longer exists and has been merged into `sdl12-compat` ([see reference](https://github.com/Homebrew/homebrew-core/pull/111081)):

```
We could just fully get rid of sdl formula and merge it into sdl12-compat. [...]

So delete sdl.rb and add "sdl": "sdl12-compat" to renames? [...]

I think so, yeah.
```

Now, old Homebrew installations seem to be aware of the renaming through a migration path from `sdl` to `sdl12-compat` (I haven't looked into the details of how the Homebrew team did this). But new Homebrew installations, who haven't followed such migration path, don't know about the existence of `sdl`.

**Comment by skyzyx** [comment]
Resolved in https://github.com/skyzyx/homebrew-ffmpeg/releases/tag/6.0.0-1.
